vim.filetype.add {
    pattern = {
        [".*/.github/workflows/.*%.yml"] = "yaml.ghaction",
        [".*/.github/workflows/.*%.yaml"] = "yaml.ghaction",
        [".*/playbooks/.*%.yml"] = "yaml.ansible",
        [".*/playbooks/.*%.yaml"] = "yaml.ansible",
        [".*/inventory/.*%.yml"] = "yaml.ansible",
        [".*/inventory/.*%.yaml"] = "yaml.ansible",
        [".*/host_vars/.*%.yml"] = "yaml.ansible",
        [".*/host_vars/.*%.yaml"] = "yaml.ansible",
        [".*/group_vars/.*%.yml"] = "yaml.ansible",
        [".*/group_vars/.*%.yaml"] = "yaml.ansible",
        [".*/roles/.*%.yml"] = "yaml.ansible",
        [".*/roles/.*%.yaml"] = "yaml.ansible",
        [".*/ansible/.*%.yml"] = "yaml.ansible",
        [".*/ansible/.*%.yaml"] = "yaml.ansible",
        [".*/roles/*/tasks/.*%.yml"] = "yaml.ansible",
        [".*/roles/*/tasks/.*%.yaml"] = "yaml.ansible",
        [".*%.ansible.yml"] = "yaml.ansible",
        [".*%.ansible.yaml"] = "yaml.ansible",
        [".*%.yml.draft"] = "yaml",
        [".*%.yaml.draft"] = "yaml",
        [".*/compose%.yaml"] = "yaml.docker-compose",
        [".*/compose%.yml"] = "yaml.docker-compose",
        ["openapi.*%.ya?ml"] = "yaml.openapi",
        ["openapi.*%.json"] = "json.openapi",
    },
}
