name: Master workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  add-plugins-md:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Authorize Git
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
      - name: Add PLUGINS.md
        uses: ./.github/actions/update-plugins-md
      - name: Commit changes
        run: |
          if git diff --exit-code; then
            echo "No changes to commit"
            exit 0
          fi
          git add PLUGINS.md
          git commit -m "chore: update PLUGINS.md"
          git push origin ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update to dotfiles repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: egemenkopuz/dotfiles
          event-type: update-submodule
